name: jira-action

on:
  push:
    branches:
      - master
      - feature/*
    paths-ignore:
      - "**README.md"

jobs:
  main:
    name: jira-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t leanixacrpublic.azurecr.io/jira-action:latest .

      - name: Docker login and push image to Docker Hub
        if: github.ref=='refs/heads/master'
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin ${{ secrets.DOCKER_HUB_SERVER }}
          docker push leanixacrpublic.azurecr.io/jira-action:latest